name: hostelway
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stacked: ^3.4.1
  google_fonts: ^5.1.0
  path_provider: ^2.0.15
  dio: ^5.3.2
  go_router: ^10.1.0
  toggle_switch: ^2.1.0
  logger: ^2.0.1
  image_picker: ^1.0.2
  bot_toast: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/images/
  uses-material-design: true
